"""Add articles and invoices with article categories

Revision ID: 893c9acdc5a5
Revises: 01aea0166868
Create Date: 2026-03-14 14:06:11.225558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893c9acdc5a5'
down_revision: Union[str, None] = '01aea0166868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_items', sa.Column('article_id', sa.Integer(), nullable=True))
    op.add_column('sales_order_items', sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales_order_items', sa.Column('item_type', sa.String(length=20), nullable=True))
    op.alter_column('sales_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'sales_order_items', 'articles', ['article_id'], ['id'])
    op.drop_column('sales_order_items', 'production_cost_per_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_items', sa.Column('production_cost_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales_order_items', type_='foreignkey')
    op.alter_column('sales_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales_order_items', 'item_type')
    op.drop_column('sales_order_items', 'cost_per_unit')
    op.drop_column('sales_order_items', 'article_id')
    # ### end Alembic commands ###
