"""Initial migration

Revision ID: d0ad62022e73
Revises: 
Create Date: 2026-02-22 11:55:19.645543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ad62022e73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ideas', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ideas', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'labor_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'labor_hours',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('ideas', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ideas', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
