"""Add linked_product_id to articles

Revision ID: 2c906de51b52
Revises: 893c9acdc5a5
Create Date: 2026-03-14 14:30:55.857145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c906de51b52'
down_revision: Union[str, None] = '893c9acdc5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('linked_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'products', ['linked_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'linked_product_id')
    # ### end Alembic commands ###
