"""Add article components and assembly fields

Revision ID: affc007960e6
Revises: f40506ead974
Create Date: 2026-03-29 14:16:55.033485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affc007960e6'
down_revision: Union[str, None] = 'f40506ead974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('labor_minutes', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('articles', sa.Column('labor_rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('articles', sa.Column('packaging_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('articles', sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'shipping_cost')
    op.drop_column('articles', 'packaging_cost')
    op.drop_column('articles', 'labor_rate_per_hour')
    op.drop_column('articles', 'labor_minutes')
    # ### end Alembic commands ###
