"""Add Config table and bank_info to invoices

Revision ID: f40506ead974
Revises: ebce17501dc8
Create Date: 2026-03-19 20:52:25.954455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40506ead974'
down_revision: Union[str, None] = 'ebce17501dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('bank_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'bank_info')
    # ### end Alembic commands ###
