"""Add discount_percent and discount_amount to invoices

Revision ID: ebce17501dc8
Revises: d8a36c3b3ff2
Create Date: 2026-03-19 19:41:24.093227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebce17501dc8'
down_revision: Union[str, None] = 'd8a36c3b3ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'discount_percent')
    # ### end Alembic commands ###
