"""Add customers table and customer_id to invoices

Revision ID: d8a36c3b3ff2
Revises: 2c906de51b52
Create Date: 2026-03-14 18:49:06.562945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a36c3b3ff2'
down_revision: Union[str, None] = '2c906de51b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'customer_id')
    # ### end Alembic commands ###
