"""Change labor_hours to labor_minutes

Revision ID: ebc23bdbbc7e
Revises: d0ad62022e73
Create Date: 2026-02-22 11:57:39.620918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc23bdbbc7e'
down_revision: Union[str, None] = 'd0ad62022e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Neue Spalte labor_minutes hinzufügen
    op.add_column('products', sa.Column('labor_minutes', sa.Numeric(precision=10, scale=2), nullable=True))
    
    # 2. Daten konvertieren: Stunden -> Minuten (x 60)
    op.execute("UPDATE products SET labor_minutes = labor_hours * 60 WHERE labor_hours IS NOT NULL")
    
    # 3. Alte Spalte labor_hours entfernen
    op.drop_column('products', 'labor_hours')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Alte Spalte labor_hours wieder hinzufügen
    op.add_column('products', sa.Column('labor_hours', sa.Numeric(precision=10, scale=4), nullable=True))
    
    # 2. Daten zurück-konvertieren: Minuten -> Stunden (/ 60)
    op.execute("UPDATE products SET labor_hours = labor_minutes / 60 WHERE labor_minutes IS NOT NULL")
    
    # 3. Neue Spalte labor_minutes entfernen
    op.drop_column('products', 'labor_minutes')
    
    # ### end Alembic commands ###
