"""Add calculation_mode, units_per_batch, machine cost_per_sheet, and SalesOrder

Revision ID: 543d8d9f5f22
Revises: ebc23bdbbc7e
Create Date: 2026-02-22 12:55:17.851291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543d8d9f5f22'
down_revision: Union[str, None] = 'ebc23bdbbc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Neue Spalten für Maschinen (Kosten pro Bogen)
    op.add_column('machines', sa.Column('cost_per_sheet', sa.Numeric(precision=10, scale=4), nullable=True))
    
    # Neue Spalten für Produkte (Berechnungsmodus)
    op.add_column('products', sa.Column('calculation_mode', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('units_per_batch', sa.Integer(), nullable=True))
    
    # Standardwerte für bestehende Produkte setzen
    op.execute("UPDATE products SET calculation_mode = 'per_unit', units_per_batch = 1 WHERE calculation_mode IS NULL")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'units_per_batch')
    op.drop_column('products', 'calculation_mode')
    op.drop_column('machines', 'cost_per_sheet')
    # ### end Alembic commands ###
