"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-19 07:07:15.701941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_config_id'), 'config', ['id'], unique=False)
    op.create_table('converted_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path_png', sa.String(length=500), nullable=False),
    sa.Column('file_path_svg', sa.String(length=500), nullable=False),
    sa.Column('original_size_bytes', sa.Integer(), nullable=True),
    sa.Column('svg_size_bytes', sa.Integer(), nullable=True),
    sa.Column('conversion_mode', sa.String(length=50), nullable=True),
    sa.Column('color_mode', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_converted_files_id'), 'converted_files', ['id'], unique=False)
    op.create_table('feedback_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_ideas_id'), 'feedback_ideas', ['id'], unique=False)
    op.create_table('machine_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_billing_mode', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("default_billing_mode IN ('time', 'sheet')", name='ck_machine_types_billing_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_machine_types_id'), 'machine_types', ['id'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_ideas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_events_id'), 'market_events', ['id'], unique=False)
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_material_types_id'), 'material_types', ['id'], unique=False)
    op.create_table('event_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_done', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_todos_id'), 'event_todos', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('machine_type_id', sa.Integer(), nullable=False),
    sa.Column('billing_mode', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("billing_mode IN ('time', 'sheet')", name='ck_machines_billing_mode'),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machine_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('yield_qty', sa.Integer(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_for_market', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('yield_qty >= 1', name='ck_products_yield_min'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('event_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('custom_vk', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_items_id'), 'event_items', ['id'], unique=False)
    op.create_table('machine_sheet_costs',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('cost_per_sheet', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.CheckConstraint('cost_per_sheet >= 0', name='ck_machine_sheet_costs_nonnegative'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_table('machine_time_costs',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('depreciation_euro', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lifespan_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('power_w', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.CheckConstraint('depreciation_euro >= 0 AND power_w >= 0', name='ck_machine_time_costs_nonnegative'),
    sa.CheckConstraint('lifespan_hours > 0', name='ck_machine_time_costs_lifespan'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_table('material_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_material_prices_nonnegative'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_prices_id'), 'material_prices', ['id'], unique=False)
    op.create_index(op.f('ix_material_prices_material_id'), 'material_prices', ['material_id'], unique=False)
    op.create_table('product_labor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('minutes >= 0 AND hourly_rate >= 0', name='ck_product_labor_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_labor_id'), 'product_labor', ['id'], unique=False)
    op.create_index(op.f('ix_product_labor_product_id'), 'product_labor', ['product_id'], unique=False)
    op.create_table('product_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_machines_id'), 'product_machines', ['id'], unique=False)
    op.create_index(op.f('ix_product_machines_machine_id'), 'product_machines', ['machine_id'], unique=False)
    op.create_index(op.f('ix_product_machines_product_id'), 'product_machines', ['product_id'], unique=False)
    op.create_table('product_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_materials_id'), 'product_materials', ['id'], unique=False)
    op.create_index(op.f('ix_product_materials_material_id'), 'product_materials', ['material_id'], unique=False)
    op.create_index(op.f('ix_product_materials_product_id'), 'product_materials', ['product_id'], unique=False)
    op.create_table('product_packaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_packaging_id'), 'product_packaging', ['id'], unique=False)
    op.create_index(op.f('ix_product_packaging_material_id'), 'product_packaging', ['material_id'], unique=False)
    op.create_index(op.f('ix_product_packaging_product_id'), 'product_packaging', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_packaging_product_id'), table_name='product_packaging')
    op.drop_index(op.f('ix_product_packaging_material_id'), table_name='product_packaging')
    op.drop_index(op.f('ix_product_packaging_id'), table_name='product_packaging')
    op.drop_table('product_packaging')
    op.drop_index(op.f('ix_product_materials_product_id'), table_name='product_materials')
    op.drop_index(op.f('ix_product_materials_material_id'), table_name='product_materials')
    op.drop_index(op.f('ix_product_materials_id'), table_name='product_materials')
    op.drop_table('product_materials')
    op.drop_index(op.f('ix_product_machines_product_id'), table_name='product_machines')
    op.drop_index(op.f('ix_product_machines_machine_id'), table_name='product_machines')
    op.drop_index(op.f('ix_product_machines_id'), table_name='product_machines')
    op.drop_table('product_machines')
    op.drop_index(op.f('ix_product_labor_product_id'), table_name='product_labor')
    op.drop_index(op.f('ix_product_labor_id'), table_name='product_labor')
    op.drop_table('product_labor')
    op.drop_index(op.f('ix_material_prices_material_id'), table_name='material_prices')
    op.drop_index(op.f('ix_material_prices_id'), table_name='material_prices')
    op.drop_table('material_prices')
    op.drop_table('machine_time_costs')
    op.drop_table('machine_sheet_costs')
    op.drop_index(op.f('ix_event_items_id'), table_name='event_items')
    op.drop_table('event_items')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_event_todos_id'), table_name='event_todos')
    op.drop_table('event_todos')
    op.drop_index(op.f('ix_material_types_id'), table_name='material_types')
    op.drop_table('material_types')
    op.drop_index(op.f('ix_market_events_id'), table_name='market_events')
    op.drop_table('market_events')
    op.drop_index(op.f('ix_machine_types_id'), table_name='machine_types')
    op.drop_table('machine_types')
    op.drop_index(op.f('ix_feedback_ideas_id'), table_name='feedback_ideas')
    op.drop_table('feedback_ideas')
    op.drop_index(op.f('ix_converted_files_id'), table_name='converted_files')
    op.drop_table('converted_files')
    op.drop_index(op.f('ix_config_id'), table_name='config')
    op.drop_table('config')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
